// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/play/:date": {
    params: {
      "date": string;
    };
  };
  "/scores": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/play/:date" | "/scores";
  };
  "./Pages/HomePage.tsx": {
    id: "home";
    page: "/";
  } | {
    id: "play";
    page: "/play/:date";
  };
  "./Pages/ScoreCardPage.tsx": {
    id: "Pages/ScoreCardPage";
    page: "/scores";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "home": typeof import("./src/./Pages/HomePage.tsx");
  "play": typeof import("./src/./Pages/HomePage.tsx");
  "Pages/ScoreCardPage": typeof import("./src/./Pages/ScoreCardPage.tsx");
};