// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/scores": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/scores";
  };
  "./Pages/HomePage.tsx": {
    id: "Pages/HomePage";
    page: "/";
  };
  "./Pages/ScoreCardPage.tsx": {
    id: "Pages/ScoreCardPage";
    page: "/scores";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "Pages/HomePage": typeof import("./src/./Pages/HomePage.tsx");
  "Pages/ScoreCardPage": typeof import("./src/./Pages/ScoreCardPage.tsx");
};